### PR TITLE
added the public files

### PR DESCRIPTION
**Pull request by NouraldinS**
Added the front end public folder having style, image and js folders.
And by mistake server index.js and app.js were updated and pushed.
RELATES #26 
files structure part of issue.

### CODE REVIEW

**Comment by matthewdking** [comment]
Unassigning myself as no team members have reviewed this yet :smile:

**Review by yahyaHB — APPROVED** [review]
classic server initiation.

**Review by sultanassi95 — APPROVED** [review]
reviewed, and approved

**Review by sultanassi95 — APPROVED** [review]
Reviewed the changes.
approved

**Review by matthewdking — APPROVED** [review]
LGTM :+1:

**Pull request merged**
